/**
 * Ontario Tenant Tools - Report View
 *
 * Generates a session summary that can be copied or printed.
 */

import { getReportData, hasCalculations } from "../utils/session";

export function render(): string {
  return `
    <section id="report" class="view-section active">
      <h2 style="margin-bottom:1rem;">Session Report</h2>

      <div class="tool-intro">
        <strong>Privacy Note:</strong> This report is generated locally in your browser. Nothing is saved online. Use "Copy" to paste into an email or "Print" to save as PDF.
      </div>

      <div id="report-content" class="report-section">
        <p style="text-align:center; color:var(--text-secondary);">
          No data entered yet. Use the tools to add information, then return here to generate a report.
        </p>
      </div>

      <div class="report-actions">
        <button class="btn-primary" id="copy-report" style="background:var(--surface-float);">
          <svg class="icon" viewBox="0 0 24 24">
            <rect x="9" y="9" width="13" height="13" rx="2" ry="2"/>
            <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/>
          </svg>
          Copy
        </button>
        <button class="btn-primary" id="print-report">
          <svg class="icon" viewBox="0 0 24 24">
            <polyline points="6 9 6 2 18 2 18 9"/>
            <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/>
            <rect x="6" y="14" width="12" height="8"/>
          </svg>
          Save PDF
        </button>
      </div>
    </section>
  `;
}

export function init(): void {
  const copyBtn = document.getElementById("copy-report");
  const printBtn = document.getElementById("print-report");

  copyBtn?.addEventListener("click", copyReport);
  printBtn?.addEventListener("click", () => window.print());

  // Generate the report content
  generateReportContent();
}

function generateReportContent(): void {
  const reportContent = document.getElementById("report-content");
  if (!reportContent) return;

  const today = new Date().toLocaleDateString("en-CA", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  // Get data from session state
  if (!hasCalculations()) {
    reportContent.innerHTML = `
      <p style="text-align:center; color:var(--text-secondary);">
        No data entered yet. Use the tools to add information, then return here to generate a report.
      </p>
    `;
    return;
  }

  const data = getReportData();

  // Tool display names
  const toolNames: Record<string, string> = {
    n4: "N4 Notice (Unpaid Rent)",
    n12: "N12 Notice (Landlord Moving In)",
    rent: "Rent Increase Check",
    review: "Eviction Order Review",
    s82: "Section 82 Deposit",
  };

  // Group items by tool for organized display
  const grouped: Record<string, Array<{ label: string; value: string }>> = {};
  for (const item of data) {
    if (!grouped[item.tool]) {
      grouped[item.tool] = [];
    }
    grouped[item.tool].push({ label: item.label, value: item.value });
  }

  let html = `
    <h3 style="margin:0 0 1rem;">Session Record - ${today}</h3>
  `;

  for (const [tool, items] of Object.entries(grouped)) {
    html += `
      <div style="margin-bottom:1.5rem;">
        <h4 style="margin:0 0 0.5rem; color:var(--brand-primary); font-size:0.9rem; text-transform:uppercase; letter-spacing:0.05em;">
          ${toolNames[tool] || tool}
        </h4>
    `;
    for (const item of items) {
      html += `
        <div class="report-row">
          <span class="report-label">${item.label}</span>
          <span class="report-val">${item.value}</span>
        </div>
      `;
    }
    html += `</div>`;
  }

  html += `
    <div style="margin-top:2rem; font-size:0.8rem; color:var(--text-secondary); border-top:1px solid rgba(255,255,255,0.1); padding-top:1rem;">
      Generated by Ontario Tenant Tools.<br>
      <strong>This is information only, not legal advice.</strong><br>
      For legal advice, contact a community legal clinic.
    </div>
  `;

  reportContent.innerHTML = html;
}

async function copyReport(): Promise<void> {
  const reportContent = document.getElementById("report-content");
  if (!reportContent) return;

  const text = reportContent.innerText;

  try {
    await navigator.clipboard.writeText(text);
    alert("Report copied to clipboard!");
  } catch {
    // Fallback for older browsers
    const textarea = document.createElement("textarea");
    textarea.value = text;
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand("copy");
    document.body.removeChild(textarea);
    alert("Report copied to clipboard!");
  }
}
